### ISSUE TITLE
Issue With KeePassDX, If i Open Database via KeePassVault

### ISSUE THREAD

**Issue by IzumiSenaSora** [aivanovski/keepassvault#279] opened 2024-10-13 11:15 UTC
### Overview

Hi!

If i Open my KeePass Database via KeePassVault then save something
I can't open my Database via KeePassDX client anymore

### How to reproduce

1. Open Database via KeePassVault
2. Save new info
3. Then exit
4. Then reopen it via KeePassDX
5. It failed
6. Before saving new info via KeePassVault
7. Opening via KeePassDX worked!

### Version

1.8.0

### Android Version

Android 14

### Device Model

Pixel XL

**Comment by aivanovski** [comment] 2024-10-14 08:30
Hi,

Thanks for detailed report. I can't reproduce this issue with new database (created in the app), could you please share additional information?

- Does this issue happen only with your personal database or does it happen on new files too?
- If this is personal database, could you share information about it: How many entries does it have? How big is database file? How old is database? Does it have files in it? How many does it have?

@IzumiSenaSora

**Comment by aivanovski** [comment] 2024-10-18 20:32
This issue should be fixed in #281 but it will not fix already affected entries in database. This means, that previously modified entries (that didn't allow KeePassDX to open the file) should be deleted.
Could you please check? Build is available [here](https://github.com/aivanovski/keepassvault/actions/runs/11409388725), you may choose any build except `app-fdroid-automation.apk`
@IzumiSenaSora

**Comment by aivanovski** [comment] 2024-10-19 14:45
I wasn't able to reproduce the bug according to your steps. But looks like I finally managed to find valid steps for it with new db:
1 - Create new db file
2 - Add entry "Entry 1"
3 - Change title of "Entry 1" -> "Entry 2"
4 - Check that KeePassDX opens db
5 - Change title of "Entry 2" -> "Entry 3"
5 - Open db with KeePassDX, it should not open it

The issue was caused by error in processing entries history, I think it should be fixed now.
Could you please check it again? So we can sure that there are no more issues with entry history. Build is available [here](https://github.com/aivanovski/keepassvault/actions/runs/11418343720) @IzumiSenaSora

**Closed** 2024-10-19 17:55 UTC
Labels: bug
